### ISSUE TITLE
Consider making the `Log` effect dynamic

### ISSUE THREAD

**Issue by michaelpj** [haskell-effectful/log-effectful#11]
We have a use-case for a dynamic version of the log effect. Namely, wanting to intercept log calls in order to perform some kind of monadic information lookup to add data to the log message. (Concrete example: looking up the current OpenTelemetry span ID)

In an ideal world we would just manage this by using `localData`, but it's not always easy to ensure you run `localData` whenever the thing you want to trace changes. So it would be nice to instead be able to do the lookup when we log, and tweaking the handler with `interpose` would let us do that.

**Comment by arybczak** [comment]
It was done a few months ago in dc1978498a260a2986db43e775140a4e220e1585, it's now on Hackage ;)

**Comment by michaelpj** [comment]
Hah, the best kind of fix is the one that's already done!
